### ISSUE TITLE
Manifest inconsistency

### ISSUE THREAD

**Issue by jaruba** [sleeyax/stremio-podcasts-addon#1]
You are using a type for your catalog:
https://github.com/sleeyax/stremio-podcasts-addon/blob/master/src/addon.js#L18

That is not declared in manifest.types:
https://github.com/sleeyax/stremio-podcasts-addon/blob/master/src/addon.js#L39

I believe this might be the reason the "Podcasts" type only shows on the Desktop app, but not in the Android app.

**Comment by sleeyax** [comment]
Oohh, I almost thought custom types were an issue with the android app. Glad I'm mistaken - thanks for your help!
